ci(docker): update docker release workflows
adds additional permission fixes, and executes dos2unix

diff --git a/.github/workflows/deploy-docker-dockerhub.yml b/.github/workflows/deploy-docker-dockerhub.yml
--- a/.github/workflows/deploy-docker-dockerhub.yml
+++ b/.github/workflows/deploy-docker-dockerhub.yml
@@ -34,7 +34,7 @@ on:
             # #
 
             IMAGE_NAME:
-                description:  "📦 Image Name"
+                description:  '📦 Image Name'
                 required:     true
                 default:      'keeweb'
                 type:         string
@@ -47,7 +47,7 @@ on:
             # #
 
             IMAGE_AUTHOR:
-                description:  "🪪 Image Author"
+                description:  '🪪 Image Author'
                 required:     true
                 default:      'antelle'
                 type:         string
@@ -59,7 +59,7 @@ on:
             # #
 
             IMAGE_VERSION:
-                description:  "🏷️ Image Version"
+                description:  '🏷️ Image Version'
                 required:     true
                 default:      '1.19.0'
                 type:         string
@@ -71,32 +71,32 @@ on:
             # #
 
             IMAGE_DOCKERHUB_USERNAME:
-                description:  "🪪 Dockerhub Username"
-                required:     true
-                default:      'antelle'
-                type:         string
+                description:    '🪪 Dockerhub Username'
+                required:       true
+                default:        'antelle'
+                type:           string
 
             # #
-            #   true:     runs all actions, even ones not scheduled
-            #   false:    only scheduled tasks will run
+            #   true            no changes to the repo will be made
+            #   false           workflow will behave normally, and push any changes detected to the files
             # #
 
-            PRINT_ONLY:
-                description:  "📑 Print Debugs Only"
-                required:     true
-                default:      false
-                type:         boolean
+            DRY_RUN:
+                description:    '🐛 Dry Run (Debug)'
+                required:       true
+                default:        false
+                type:           boolean
 
             # #
-            #   ENABLE:       released version will be marked as beta and receive beta tag for docker
-            #   DISABLE:      release version will be marked as stable / normal release
+            #   true            released version will be marked as a development build and will have the v1.x.x-development tag instead of -latest
+            #   false           release version will be marked with -latest docker tag
             # #
 
             DEV_RELEASE:
-                description:  "🧪 Development Release"
-                required:     true
-                default:      false
-                type:         boolean
+                description:    '🧪 Development Release'
+                required:       true
+                default:        false
+                type:           boolean
 
     # #
     #   Trigger › Push
@@ -134,7 +134,7 @@ jobs:
 
     job-docker-release-tags-create:
         name: >-
-          📦 Release › Create Tag
+            📦 Release › Create Tag
         runs-on: ubuntu-latest
         permissions:
             contents: write
@@ -147,8 +147,8 @@ jobs:
             #   Release › Tags › Start
             # #
 
-            - name: "✅ Start"
-              id: task_ctags_start
+            - name: '🏳️ Start'
+              id: task_release_tags_start
               run: |
                   echo "Creating Tag"
 
@@ -156,27 +156,29 @@ jobs:
             #   Release › Tags › Checkout
             # #
 
-            - name: "☑️ Checkout"
-              id: task_ctags_checkout
+            - name: '✅ Checkout'
+              id: task_release_tags_checkout
               uses: actions/checkout@v4
               with:
                   fetch-depth: 0
 
             # #
-            #   Release › Tags › Check Permissions
+            #   Release › Tags › Fix Permissions
             # #
 
-            - name: 'Check Permissions'
+            - name: '#️⃣ Manage Permissions'
+              id: task_release_tags_permissions
               run: |
                   find ./ -name 'run' -exec chmod 755 {} \;
                   WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
                   if [ -n "${WRONG_PERM}" ]; then
+                      echo "⚠️⚠️⚠️ Permissions are invalid ⚠️⚠️⚠️"
                       for i in ${WRONG_PERM}; do
                       echo "::error file=${i},line=1,title=Missing Executable Bit::This file needs to be set as executable!"
                       done
                       exit 1
                   else
-                      echo "**** Executable permissions are OK ****"
+                      echo "✅✅✅ Executable permissions are OK ✅✅✅"
                   fi
 
             # #
@@ -186,8 +188,8 @@ jobs:
             # #
 
             - uses: rickstaa/action-create-tag@v1
-              id: task_ctags_create
-              if: ( github.event_name != 'workflow_dispatch' && inputs.PRINT_ONLY == false )
+              id: task_release_tags_create
+              if: ( github.event_name != 'workflow_dispatch' && inputs.DRY_RUN == false )
               with:
                   tag: "${{ env.IMAGE_VERSION }}"
                   tag_exists_error: false
@@ -199,9 +201,9 @@ jobs:
     #   Job › Docker Release › Dockerhub › Arm64
     # #
 
-    job-docker-release-github-arm64:
+    job-docker-release-dockerhub-arm64:
         name: >-
-          📦 Release › Dockerhub › Arm64
+            📦 Release › Dockerhub › Arm64
         runs-on: ubuntu-latest
         needs: [ job-docker-release-tags-create ]
         permissions:
@@ -215,43 +217,65 @@ jobs:
             #   Release › Dockerhub › Start › Arm64
             # #
 
-            - name: "✅ Start"
+            - name: '🏳️ Start'
               id: task_release_dh_start
               run: |
-                  echo "Starting Dockerhub Docker arm64"
+                  echo "Starting Dockerhub arm64"
 
             # #
             #   Release › Dockerhub › Checkout › Arm64
             # #
 
-            - name: "☑️ Checkout"
+            - name: '✅ Checkout'
               id: task_release_dh_checkout
               uses: actions/checkout@v4
               with:
                   fetch-depth: 0
 
             # #
-            #   Release › Dockerhub › Check Permissions
+            #   Release › Dockerhub › Install Dependencies
             # #
 
-            - name: 'Check Permissions'
+            - name: '📦 Install Dependencies'
+              id: task_release_dh_dependencies
+              run:
+                  sudo apt-get install -qq dos2unix
+
+            # #
+            #   Release › Dockerhub › Execute dos2unix
+            # #
+
+            - name: '🔐 Apply dos2unix'
+              id: task_release_dh_dos2unix
+              run: |
+                  echo "⚠️⚠️⚠️ Running DOS2UNIX ⚠️⚠️⚠️"
+                  find ./ \( -path "./.git" -o -path "./docs" -o -path "./.github" -o -path "*.png" -o -path "*.jpg" \) -prune -o -name '*' -print | xargs dos2unix --
+                  echo "✅✅✅ Completed DOS2UNIX ✅✅✅"
+
+            # #
+            #   Release › Dockerhub › Fix Permissions
+            # #
+
+            - name: '#️⃣ Manage Permissions'
+              id: task_release_dh_permissions
               run: |
                   find ./ -name 'run' -exec chmod 755 {} \;
                   WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
                   if [ -n "${WRONG_PERM}" ]; then
+                      echo "⚠️⚠️⚠️ Permissions are invalid ⚠️⚠️⚠️"
                       for i in ${WRONG_PERM}; do
                       echo "::error file=${i},line=1,title=Missing Executable Bit::This file needs to be set as executable!"
                       done
                       exit 1
                   else
-                      echo "**** Executable permissions are OK ****"
+                      echo "✅✅✅ Executable permissions are OK ✅✅✅"
                   fi
 
             # #
             #   Release › Dockerhub › QEMU › Arm64
             # #
 
-            - name: "⚙️ Set up QEMU"
+            - name: '⚙️ Set up QEMU'
               id: task_release_dh_qemu
               uses: docker/setup-qemu-action@v3
 
@@ -259,18 +283,18 @@ jobs:
             #   Release › Dockerhub › Setup BuildX › Arm64
             # #
 
-            - name: "⚙️ Setup Buildx"
+            - name: '⚙️ Setup Buildx'
               id: task_release_dh_buildx
               uses: docker/setup-buildx-action@v3
               with:
                   version: latest
-                  driver-opts: 'image=moby/buildkit:v0.10.5'
+                  driver-opts: 'image=moby/buildkit:latest'
 
             # #
             #   Release › Dockerhub › Registry Login › Arm64
             # #
 
-            - name: "⚙️ Login to Dockerhub"
+            - name: '⚙️ Login to Dockerhub'
               id: task_release_dh_registry
               uses: docker/login-action@v3
               with:
@@ -281,14 +305,13 @@ jobs:
             #   Release › Dockerhub › Meta › Arm64
             # #
 
-            - name: "🔨 Dockerhub: Meta - Arm64"
+            - name: '🔨 Dockerhub: Meta - Arm64'
               id: task_release_dh_meta
               uses: docker/metadata-action@v5
               with:
                   images: |
                       ${{ env.IMAGE_AUTHOR }}/${{ env.IMAGE_NAME }}
                   tags: |
-
                       #  latest no
                       type=raw,value=latest,enable=false
 
@@ -304,17 +327,18 @@ jobs:
                       latest=false
 
             # #
-            #   Release › Dockerhub › Debug › Arm64
+            #   Release › Dockerhub › Checkpoint › Arm64
             # #
 
-            - name: "🪪 Debug › Print"
-              id: task_release_dh_print
+            - name: '⚠️ Checkpoint'
+              id: task_release_dh_checkpoint
               run: |
-                  echo "registry ............. Dockerhub"
+                  echo "registry ............. Github"
                   echo "github.actor.......... ${{ github.actor }}"
                   echo "github.ref ........... ${{ github.ref }}"
+                  echo "github.ref_name ...... ${{ github.ref_name }}"
                   echo "github.event_name .... ${{ github.event_name }}"
-                  echo "inputs.PRINT_ONLY .... ${{ inputs.PRINT_ONLY }}"
+                  echo "inputs.DRY_RUN ....... ${{ inputs.DRY_RUN }}"
                   echo "env.AUTHOR ........... ${{ env.IMAGE_AUTHOR }}"
                   echo "tags ................. ${{ steps.task_release_dh_meta.outputs.tags }}"
                   echo "labels ............... ${{ steps.task_release_dh_meta.outputs.labels }}"
@@ -323,10 +347,10 @@ jobs:
             #   Release › Dockerhub › Build and Push › Arm64
             # #
 
-            - name: "📦 Build & Push (linux/arm64)"
+            - name: '📦 Build & Push (linux/arm64)'
               id: task_release_dh_push
               uses: docker/build-push-action@v6
-              if: ( github.event_name == 'workflow_dispatch' && inputs.PRINT_ONLY == false ) || ( github.event_name == 'push' )
+              if: ( github.event_name == 'workflow_dispatch' && inputs.DRY_RUN == false ) || ( github.event_name == 'push' )
               with:
                   context: .
                   file: Dockerfile.aarch64
@@ -339,7 +363,7 @@ jobs:
     #   Job › Docker Release › Dockerhub › Amd64
     # #
 
-    job-docker-release-github-amd64:
+    job-docker-release-dockerhub-amd64:
         name: >-
           📦 Release › Dockerhub › Amd64
         runs-on: ubuntu-latest
@@ -348,14 +372,14 @@ jobs:
             packages: write
             attestations: write
             id-token: write
-        needs: [ job-docker-release-tags-create, job-docker-release-github-arm64 ]
+        needs: [ job-docker-release-tags-create, job-docker-release-dockerhub-arm64 ]
         steps:
 
             # #
             #   Release › Dockerhub › Start › Amd64
             # #
 
-            - name: "✅ Start"
+            - name: '🏳️ Start'
               id: task_release_dh_start
               run: |
                   echo "Starting Dockerhub docker release"
@@ -364,34 +388,54 @@ jobs:
             #   Release › Dockerhub › Checkout › Amd64
             # #
 
-            - name: "☑️ Checkout"
+            - name: '✅ Checkout'
               id: task_release_dh_checkout
               uses: actions/checkout@v4
               with:
                   fetch-depth: 0
 
             # #
-            #   Release › Dockerhub › Check Permissions
+            #   Release › Dockerhub › Install Dependencies
             # #
 
-            - name: 'Check Permissions'
+            - name: '📦 Install Dependencies'
+              id: task_release_dh_dependencies
+              run:
+                  sudo apt-get install -qq dos2unix
+
+            # #
+            #   Release › Dockerhub › Execute dos2unix
+            # #
+
+            - name: '🔐 Apply dos2unix'
+              id: task_release_dh_dos2unix
+              run: |
+                  find ./ \( -path "./.git" -o -path "./docs" -o -path "./.github" -o -path "*.png" -o -path "*.jpg" \) -prune -o -name '*' -print | xargs dos2unix --
+                  
+            # #
+            #   Release › Dockerhub › Fix Permissions
+            # #
+
+            - name: '#️⃣ Manage Permissions'
+              id: task_release_dh_permissions
               run: |
                   find ./ -name 'run' -exec chmod 755 {} \;
                   WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
                   if [ -n "${WRONG_PERM}" ]; then
+                      echo "⚠️⚠️⚠️ Permissions are invalid ⚠️⚠️⚠️"
                       for i in ${WRONG_PERM}; do
                       echo "::error file=${i},line=1,title=Missing Executable Bit::This file needs to be set as executable!"
                       done
                       exit 1
                   else
-                      echo "**** Executable permissions are OK ****"
+                      echo "✅✅✅ Executable permissions are OK ✅✅✅"
                   fi
 
             # #
             #   Release › Dockerhub › QEMU › Amd64
             # #
 
-            - name: "⚙️ Set up QEMU"
+            - name: '⚙️ Set up QEMU'
               id: task_release_dh_qemu
               uses: docker/setup-qemu-action@v3
 
@@ -399,18 +443,18 @@ jobs:
             #   Release › Dockerhub › Setup BuildX › Amd64
             # #
 
-            - name: "⚙️ Setup Buildx"
+            - name: '⚙️ Setup Buildx'
               id: task_release_dh_buildx
               uses: docker/setup-buildx-action@v3
               with:
                   version: latest
-                  driver-opts: 'image=moby/buildkit:v0.10.5'
+                  driver-opts: 'image=moby/buildkit:latest'
 
             # #
             #   Release › Dockerhub › Registry Login › Amd64
             # #
 
-            - name: "⚙️ Login to Dockerhub"
+            - name: '⚙️ Login to Dockerhub'
               id: task_release_dh_registry
               uses: docker/login-action@v3
               with:
@@ -421,7 +465,7 @@ jobs:
             #   Release › Dockerhub › Meta › Amd64
             # #
 
-            - name: "🔨 Dockerhub: Meta - Amd64"
+            - name: '🔨 Dockerhub: Meta - Amd64'
               id: task_release_dh_meta
               uses: docker/metadata-action@v5
               with:
@@ -446,17 +490,18 @@ jobs:
                       latest=${{ !inputs.DEV_RELEASE }}
 
             # #
-            #   Release › Dockerhub › Debug › Amd64
+            #   Release › Dockerhub › Checkpoint › Amd64
             # #
 
-            - name: "🪪 Debug › Print"
-              id: task_release_dh_print
+            - name: '⚠️ Checkpoint'
+              id: task_release_dh_checkpoint
               run: |
-                  echo "registry ............. Dockerhub"
+                  echo "registry ............. Github"
                   echo "github.actor.......... ${{ github.actor }}"
                   echo "github.ref ........... ${{ github.ref }}"
+                  echo "github.ref_name ...... ${{ github.ref_name }}"
                   echo "github.event_name .... ${{ github.event_name }}"
-                  echo "inputs.PRINT_ONLY .... ${{ inputs.PRINT_ONLY }}"
+                  echo "inputs.DRY_RUN ....... ${{ inputs.DRY_RUN }}"
                   echo "env.AUTHOR ........... ${{ env.IMAGE_AUTHOR }}"
                   echo "tags ................. ${{ steps.task_release_dh_meta.outputs.tags }}"
                   echo "labels ............... ${{ steps.task_release_dh_meta.outputs.labels }}"
@@ -465,10 +510,10 @@ jobs:
             #   Release › Dockerhub › Build and Push › Amd64
             # #
 
-            - name: "📦 Build & Push (linux/amd64)"
+            - name: '📦 Build & Push (linux/amd64)'
               id: task_release_dh_push
               uses: docker/build-push-action@v6
-              if: ( github.event_name == 'workflow_dispatch' && inputs.PRINT_ONLY == false ) || ( github.event_name == 'push' )
+              if: ( github.event_name == 'workflow_dispatch' && inputs.DRY_RUN == false ) || ( github.event_name == 'push' )
               with:
                   context: .
                   file: Dockerfile
