ci(docker): update deployment workflows
add additional checks to run dos2unix and permission checks

diff --git a/.github/workflows/deploy-docker-github.yml b/.github/workflows/deploy-docker-github.yml
--- a/.github/workflows/deploy-docker-github.yml
+++ b/.github/workflows/deploy-docker-github.yml
@@ -34,7 +34,7 @@ on:
             # #
 
             IMAGE_NAME:
-                description:  "📦 Image Name"
+                description:  '📦 Image Name'
                 required:     true
                 default:      'keeweb'
                 type:         string
@@ -47,7 +47,7 @@ on:
             # #
 
             IMAGE_AUTHOR:
-                description:  "🪪 Image Author"
+                description:  '🪪 Image Author'
                 required:     true
                 default:      'keeweb'
                 type:         string
@@ -59,7 +59,7 @@ on:
             # #
 
             IMAGE_VERSION:
-                description:  "🏷️ Image Version"
+                description:  '🏷️ Image Version'
                 required:     true
                 default:      '1.19.0'
                 type:         string
@@ -71,32 +71,32 @@ on:
             # #
 
             IMAGE_GHCR_USERNAME:
-                description:  "🪪 ghcr.io Username"
-                required:     true
-                default:      'keeweb'
-                type:         string
+                description:    '🪪 ghcr.io Username'
+                required:       true
+                default:        'keeweb'
+                type:           string
 
             # #
-            #   true:     runs all actions, even ones not scheduled
-            #   false:    only scheduled tasks will run
+            #   true            no changes to the repo will be made
+            #   false           workflow will behave normally, and push any changes detected to the files
             # #
 
-            PRINT_ONLY:
-                description:  "📑 Print Debugs Only"
-                required:     true
-                default:      false
-                type:         boolean
+            DRY_RUN:
+                description:    '🐛 Dry Run (Debug)'
+                required:       true
+                default:        false
+                type:           boolean
 
             # #
-            #   ENABLE:       released version will be marked as beta and receive beta tag for docker
-            #   DISABLE:      release version will be marked as stable / normal release
+            #   true            released version will be marked as a development build and will have the v1.x.x-development tag instead of -latest
+            #   false           release version will be marked with -latest docker tag
             # #
 
             DEV_RELEASE:
-                description:  "🧪 Development Release"
-                required:     true
-                default:      false
-                type:         boolean
+                description:    '🧪 Development Release'
+                required:       true
+                default:        false
+                type:           boolean
 
     # #
     #   Trigger › Push
@@ -134,7 +134,7 @@ jobs:
 
     job-docker-release-tags-create:
         name: >-
-          📦 Release › Create Tag
+            📦 Release › Create Tag
         runs-on: ubuntu-latest
         permissions:
             contents: write
@@ -147,8 +147,8 @@ jobs:
             #   Release › Tags › Start
             # #
 
-            - name: "✅ Start"
-              id: task_ctags_start
+            - name: '🏳️ Start'
+              id: task_release_tags_start
               run: |
                   echo "Creating Tag"
 
@@ -156,27 +156,29 @@ jobs:
             #   Release › Tags › Checkout
             # #
 
-            - name: "☑️ Checkout"
-              id: task_ctags_checkout
+            - name: '✅ Checkout'
+              id: task_release_tags_checkout
               uses: actions/checkout@v4
               with:
                   fetch-depth: 0
 
             # #
-            #   Release › Tags › Check Permissions
+            #   Release › Tags › Fix Permissions
             # #
 
-            - name: 'Check Permissions'
+            - name: '#️⃣ Manage Permissions'
+              id: task_release_tags_permissions
               run: |
                   find ./ -name 'run' -exec chmod 755 {} \;
                   WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
                   if [ -n "${WRONG_PERM}" ]; then
+                      echo "⚠️⚠️⚠️ Permissions are invalid ⚠️⚠️⚠️"
                       for i in ${WRONG_PERM}; do
                       echo "::error file=${i},line=1,title=Missing Executable Bit::This file needs to be set as executable!"
                       done
                       exit 1
                   else
-                      echo "**** Executable permissions are OK ****"
+                      echo "✅✅✅ Executable permissions are OK ✅✅✅"
                   fi
 
             # #
@@ -186,8 +188,8 @@ jobs:
             # #
 
             - uses: rickstaa/action-create-tag@v1
-              id: task_ctags_create
-              if: ( github.event_name != 'workflow_dispatch' && inputs.PRINT_ONLY == false )
+              id: task_release_tags_create
+              if: ( github.event_name != 'workflow_dispatch' && inputs.DRY_RUN == false )
               with:
                   tag: "${{ env.IMAGE_VERSION }}"
                   tag_exists_error: false
@@ -201,7 +203,7 @@ jobs:
 
     job-docker-release-github-arm64:
         name: >-
-          📦 Release › Github › Arm64
+            📦 Release › Github › Arm64
         runs-on: ubuntu-latest
         needs: [ job-docker-release-tags-create ]
         permissions:
@@ -215,7 +217,7 @@ jobs:
             #   Release › Github › Start › Arm64
             # #
 
-            - name: "✅ Start"
+            - name: '🏳️ Start'
               id: task_release_gh_start
               run: |
                   echo "Starting Github Docker arm64"
@@ -224,34 +226,56 @@ jobs:
             #   Release › Github › Checkout › Arm64
             # #
 
-            - name: "☑️ Checkout"
+            - name: '✅ Checkout'
               id: task_release_gh_checkout
               uses: actions/checkout@v4
               with:
                   fetch-depth: 0
 
             # #
-            #   Release › Github › Check Permissions
+            #   Release › Github › Install Dependencies
             # #
 
-            - name: 'Check Permissions'
+            - name: '📦 Install Dependencies'
+              id: task_release_gh_dependencies
+              run:
+                  sudo apt-get install -qq dos2unix
+
+            # #
+            #   Release › Github › Execute dos2unix
+            # #
+
+            - name: '🔐 Apply dos2unix'
+              id: task_release_gh_dos2unix
+              run: |
+                  echo "⚠️⚠️⚠️ Running DOS2UNIX ⚠️⚠️⚠️"
+                  find ./ \( -path "./.git" -o -path "./docs" -o -path "./.github" -o -path "*.png" -o -path "*.jpg" \) -prune -o -name '*' -print | xargs dos2unix --
+                  echo "✅✅✅ Completed DOS2UNIX ✅✅✅"
+
+            # #
+            #   Release › Github › Fix Permissions
+            # #
+
+            - name: '#️⃣ Manage Permissions'
+              id: task_release_gh_permissions
               run: |
                   find ./ -name 'run' -exec chmod 755 {} \;
                   WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
                   if [ -n "${WRONG_PERM}" ]; then
+                      echo "⚠️⚠️⚠️ Permissions are invalid ⚠️⚠️⚠️"
                       for i in ${WRONG_PERM}; do
                       echo "::error file=${i},line=1,title=Missing Executable Bit::This file needs to be set as executable!"
                       done
                       exit 1
                   else
-                      echo "**** Executable permissions are OK ****"
+                      echo "✅✅✅ Executable permissions are OK ✅✅✅"
                   fi
 
             # #
             #   Release › Github › QEMU › Arm64
             # #
 
-            - name: "⚙️ Set up QEMU"
+            - name: '⚙️ Set up QEMU'
               id: task_release_gh_qemu
               uses: docker/setup-qemu-action@v3
 
@@ -259,18 +283,18 @@ jobs:
             #   Release › Github › Setup BuildX › Arm64
             # #
 
-            - name: "⚙️ Setup Buildx"
+            - name: '⚙️ Setup Buildx'
               id: task_release_gh_buildx
               uses: docker/setup-buildx-action@v3
               with:
                   version: latest
-                  driver-opts: 'image=moby/buildkit:v0.10.5'
+                  driver-opts: 'image=moby/buildkit:latest'
 
             # #
             #   Release › Github › Registry Login › Arm64
             # #
 
-            - name: "⚙️ Login to Github"
+            - name: '⚙️ Login to Github'
               id: task_release_gh_registry
               uses: docker/login-action@v3
               with:
@@ -282,7 +306,7 @@ jobs:
             #   Release › Github › Meta › Arm64
             # #
 
-            - name: "🔨 Github: Meta - Arm64"
+            - name: '🔨 Github: Meta - Arm64'
               id: task_release_gh_meta
               uses: docker/metadata-action@v5
               with:
@@ -301,17 +325,18 @@ jobs:
                       latest=false
 
             # #
-            #   Release › Github › Debug › Arm64
+            #   Release › Github › Checkpoint › Arm64
             # #
 
-            - name: "🪪 Debug › Print"
-              id: task_release_gh_print
+            - name: '⚠️ Checkpoint'
+              id: task_release_gh_checkpoint
               run: |
                   echo "registry ............. Github"
                   echo "github.actor.......... ${{ github.actor }}"
                   echo "github.ref ........... ${{ github.ref }}"
+                  echo "github.ref_name ...... ${{ github.ref_name }}"
                   echo "github.event_name .... ${{ github.event_name }}"
-                  echo "inputs.PRINT_ONLY .... ${{ inputs.PRINT_ONLY }}"
+                  echo "inputs.DRY_RUN ....... ${{ inputs.DRY_RUN }}"
                   echo "env.AUTHOR ........... ${{ env.IMAGE_AUTHOR }}"
                   echo "tags ................. ${{ steps.task_release_gh_meta.outputs.tags }}"
                   echo "labels ............... ${{ steps.task_release_gh_meta.outputs.labels }}"
@@ -320,10 +345,10 @@ jobs:
             #   Release › Github › Build and Push › Arm64
             # #
 
-            - name: "📦 Build & Push (linux/arm64)"
+            - name: '📦 Build & Push (linux/arm64)'
               id: task_release_gh_push
               uses: docker/build-push-action@v6
-              if: ( github.event_name == 'workflow_dispatch' && inputs.PRINT_ONLY == false ) || ( github.event_name == 'push' )
+              if: ( github.event_name == 'workflow_dispatch' && inputs.DRY_RUN == false ) || ( github.event_name == 'push' )
               with:
                   context: .
                   file: Dockerfile.aarch64
@@ -338,7 +363,7 @@ jobs:
 
     job-docker-release-github-amd64:
         name: >-
-          📦 Release › Github › Amd64
+            📦 Release › Github › Amd64
         runs-on: ubuntu-latest
         permissions:
             contents: write
@@ -352,7 +377,7 @@ jobs:
             #   Release › Github › Start › Amd64
             # #
 
-            - name: "✅ Start"
+            - name: '🏳️ Start'
               id: task_release_gh_start
               run: |
                   echo "Starting Github docker release"
@@ -361,34 +386,54 @@ jobs:
             #   Release › Github › Checkout › Amd64
             # #
 
-            - name: "☑️ Checkout"
+            - name: '✅ Checkout'
               id: task_release_gh_checkout
               uses: actions/checkout@v4
               with:
                   fetch-depth: 0
 
             # #
-            #   Release › Github › Check Permissions
+            #   Release › Github › Install Dependencies
             # #
 
-            - name: 'Check Permissions'
+            - name: '📦 Install Dependencies'
+              id: task_release_gh_dependencies
+              run:
+                  sudo apt-get install -qq dos2unix
+
+            # #
+            #   Release › Github › Execute dos2unix
+            # #
+
+            - name: '🔐 Apply dos2unix'
+              id: task_release_gh_dos2unix
+              run: |
+                  find ./ \( -path "./.git" -o -path "./docs" -o -path "./.github" -o -path "*.png" -o -path "*.jpg" \) -prune -o -name '*' -print | xargs dos2unix --
+
+            # #
+            #   Release › Github › Fix Permissions
+            # #
+
+            - name: '#️⃣ Manage Permissions'
+              id: task_release_gh_permissions
               run: |
                   find ./ -name 'run' -exec chmod 755 {} \;
                   WRONG_PERM=$(find ./  -path "./.git" -prune -o \( -name "run" -o -name "finish" -o -name "check" \) -not -perm -u=x,g=x,o=x -print)
                   if [ -n "${WRONG_PERM}" ]; then
+                      echo "⚠️⚠️⚠️ Permissions are invalid ⚠️⚠️⚠️"
                       for i in ${WRONG_PERM}; do
                       echo "::error file=${i},line=1,title=Missing Executable Bit::This file needs to be set as executable!"
                       done
                       exit 1
                   else
-                      echo "**** Executable permissions are OK ****"
+                      echo "✅✅✅ Executable permissions are OK ✅✅✅"
                   fi
 
             # #
             #   Release › Github › QEMU › Amd64
             # #
 
-            - name: "⚙️ Set up QEMU"
+            - name: '⚙️ Set up QEMU'
               id: task_release_gh_qemu
               uses: docker/setup-qemu-action@v3
 
@@ -396,18 +441,18 @@ jobs:
             #   Release › Github › Setup BuildX › Amd64
             # #
 
-            - name: "⚙️ Setup Buildx"
+            - name: '⚙️ Setup Buildx'
               id: task_release_gh_buildx
               uses: docker/setup-buildx-action@v3
               with:
                   version: latest
-                  driver-opts: 'image=moby/buildkit:v0.10.5'
+                  driver-opts: 'image=moby/buildkit:latest'
 
             # #
             #   Release › Github › Registry Login › Amd64
             # #
 
-            - name: "⚙️ Login to Github"
+            - name: '⚙️ Login to Github'
               id: task_release_gh_registry
               uses: docker/login-action@v3
               with:
@@ -419,7 +464,7 @@ jobs:
             #   Release › Github › Meta › Amd64
             # #
 
-            - name: "🔨 Github: Meta - Amd64"
+            - name: '🔨 Github: Meta - Amd64'
               id: task_release_gh_meta
               uses: docker/metadata-action@v5
               with:
@@ -440,17 +485,18 @@ jobs:
                       latest=${{ !inputs.DEV_RELEASE }}
 
             # #
-            #   Release › Github › Debug › Amd64
+            #   Release › Github › Checkpoint › Amd64
             # #
 
-            - name: "🪪 Debug › Print"
-              id: task_release_gh_print
+            - name: '⚠️ Checkpoint'
+              id: task_release_gh_checkpoint
               run: |
                   echo "registry ............. Github"
                   echo "github.actor.......... ${{ github.actor }}"
                   echo "github.ref ........... ${{ github.ref }}"
+                  echo "github.ref_name ...... ${{ github.ref_name }}"
                   echo "github.event_name .... ${{ github.event_name }}"
-                  echo "inputs.PRINT_ONLY .... ${{ inputs.PRINT_ONLY }}"
+                  echo "inputs.DRY_RUN ....... ${{ inputs.DRY_RUN }}"
                   echo "env.AUTHOR ........... ${{ env.IMAGE_AUTHOR }}"
                   echo "tags ................. ${{ steps.task_release_gh_meta.outputs.tags }}"
                   echo "labels ............... ${{ steps.task_release_gh_meta.outputs.labels }}"
@@ -459,10 +505,10 @@ jobs:
             #   Release › Github › Build and Push › Amd64
             # #
 
-            - name: "📦 Build & Push (linux/amd64)"
+            - name: '📦 Build & Push (linux/amd64)'
               id: task_release_gh_push
               uses: docker/build-push-action@v6
-              if: ( github.event_name == 'workflow_dispatch' && inputs.PRINT_ONLY == false ) || ( github.event_name == 'push' )
+              if: ( github.event_name == 'workflow_dispatch' && inputs.DRY_RUN == false ) || ( github.event_name == 'push' )
               with:
                   context: .
                   file: Dockerfile
